# Site settings
title: "白云城主"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://baiyun1102.github.io" # the base hostname & protocol for your site
github_username: baiyun1102

timezone: Shanghai
plugins: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

#markdown: kramdown
markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

paginate: 25

github: [metadata]
