# Site settings
title: "白云城主"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://baiyun1102.github.io" # the base hostname & protocol for your site
github_username: baiyun1102

timezone: Shanghai
plugins: ['jekyll-paginate']

# Build settings
highlighter: rouge
permalink: /:categories/:title/

markdown: kramdown
#markdown: redcarpet
redcarpet:
  extensions: ['fenced_code_blocks', 'tables']

#kramdown:
#  input:                     GFM
#  auto_ids:                  true
#  footnote_nr:               1
#  entity_output:             as_char
#  toc_levels:                1..6
#  smart_quotes:              lsquo,rsquo,ldquo,rdquo
#  enable_coderay:            false
#  hard_wrap:                 false
#  syntax_highlighter:        rouge
#  transliterated_header_ids: true
#  footnote_backlink:         "&#8617;&#xfe0e;"


paginate: 25

github: [metadata]
